### ISSUE TITLE
npm install fails on nfs

### ISSUE THREAD

**Issue by kdemarest** [appsoma/welder#35] opened 2015-05-27 14:20 UTC
Here is a simple repro case.

On mesos.appsoma.com, as user oink54321, from ~
```
mkdir badnfs
cd badnfs/
git clone https://github.com/appsoma/welder
cd welder
git checkout -b reorg origin/reorg
npm install
```
The actual problem seems to be here:
```
flock: ./Release/linker.lock: Bad file descriptor
```
Here is a more detailed output showing the problem:
```
make: Entering directory `/home/oink54321/badnfs/welder/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
flock: ./Release/linker.lock: Bad file descriptor
make: *** [Release/obj.target/bson.node] Error 65
make: Leaving directory `/home/oink54321/badnfs/welder/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/oink54321/.nvm/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-37-generic
gyp ERR! command "/home/oink54321/.nvm/v0.12.4/bin/node" "/home/oink54321/.nvm/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/oink54321/badnfs/welder/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" "--module_name=bson" "--module_path=/home/oink54321/badnfs/welder/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext/build/Release"
gyp ERR! cwd /home/oink54321/badnfs/welder/node_modules/mongodb/node_modules/mongodb-core/node_modules/bson/node_modules/bson-ext
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
```

**Comment by vernonm** [comment] 2015-05-27 14:47
The solution is to add the right linker variable:
`export LINK=g++; npm install`

The problem is a poor design for the module build process, which depends on "flock" which you can disable.  Apparently, there's no plan to enforce using g++ as the linker directly.
https://github.com/TooTallNate/node-gyp/issues/147

**Comment by zsimpson** [comment] 2015-05-29 18:37
I added this to docs and it seems to work. Closing.

**Closed by zsimpson** 2015-05-29 18:37 UTC
Labels: bug, wontfix, workaround
